import { Conflict, ExecutionFailed, HumanActionRequired, PolicyViolation, UnsupportedOperation } from '../../../core/src/errors.js';
import type { CommandRunner } from '../../../execution-engine/src/command-runner.js';
import type { DestructiveAuthorization, Resource } from '../../../schemas/src/index.js';
export * from './actions-dispatcher.js';

export interface GitHubRepositoryMetadata {nameWithOwner:string;url:string;isPrivate:boolean;defaultBranch:string;viewerPermission:string;}
export interface GitHubCiStatus {success:boolean;status:string;conclusion?:string;url?:string;databaseId?:number;}
export class LiveGitHubAdapter {
  constructor(private commands:CommandRunner){}
  async authenticatedIdentity(cwd:string,correlationId:string){const result=await this.run(cwd,correlationId,['api','user','--jq','.login']);if(result.exitCode!==0)throw new HumanActionRequired('GitHub login/OAuth is required',{officialCommand:'gh auth login --web --hostname github.com'});return result.stdout.trim();}
  async createSandboxRepository(account:Resource,input:{workspace:string;name:string;description:string;correlationId:string}):Promise<GitHubRepositoryMetadata>{
    assertAccount(account);assertSandboxName(input.name);const identity=await this.authenticatedIdentity(input.workspace,input.correlationId);if(identity.toLowerCase()!==account.externalReference.toLowerCase())throw new HumanActionRequired('Active GitHub identity does not match the explicitly confirmed sandbox account',{expected:account.externalReference,actual:identity,officialCommand:'gh auth switch --hostname github.com --user <sandbox-account>'});const fullName=`${identity}/${input.name}`;const exists=await this.run(input.workspace,input.correlationId,['repo','view',fullName,'--json','nameWithOwner']);if(exists.exitCode===0)throw new Conflict('Refusing to adopt an existing repository during bootstrap',{repository:fullName});const created=await this.run(input.workspace,input.correlationId,['repo','create',fullName,'--private','--source',input.workspace,'--remote','origin','--push','--description',input.description]);if(created.exitCode!==0)throw new ExecutionFailed('GitHub repository creation/push failed',{stderr:created.stderr});return this.metadata(account,input.workspace,fullName,input.correlationId);
  }
  async registerExistingSandboxRepository(account:Resource,input:{workspace:string;repository:string;correlationId:string}):Promise<GitHubRepositoryMetadata>{assertAccount(account);assertOwnedRepository(account,input.repository);await this.assertActiveOwner(account,input.workspace,input.correlationId);const metadata=await this.metadata(account,input.workspace,input.repository,input.correlationId);if(!metadata.isPrivate||metadata.viewerPermission!=='ADMIN')throw new PolicyViolation('Existing sandbox repository must be private and grant ADMIN permission',{repository:input.repository,isPrivate:metadata.isPrivate,viewerPermission:metadata.viewerPermission});return metadata;}
  async connectAndPushEmptyRepository(repository:Resource,input:{workspace:string;branch:string;correlationId:string}){assertRepository(repository);await this.assertActiveRepositoryOwner(repository,input.workspace,input.correlationId);const expected=`https://github.com/${repository.externalReference}.git`;const current=await this.commands.run({command:'git',args:['remote','get-url','origin'],cwd:input.workspace,taskId:input.correlationId,allowed:['READ']});if(current.record.exitCode===0&&normalizeRemote(current.stdout.trim())!==normalizeRemote(expected))throw new PolicyViolation('Existing origin does not match the registered sandbox repository',{expected,actual:current.stdout.trim()});if(current.record.exitCode!==0){const add=await this.commands.run({command:'git',args:['remote','add','origin',expected],cwd:input.workspace,taskId:input.correlationId,allowed:['BUILD']});if(add.record.exitCode!==0)throw new ExecutionFailed('Failed to attach registered sandbox origin',{stderr:add.stderr});}const remote=await this.commands.run({command:'git',args:['ls-remote','--heads','origin'],cwd:input.workspace,taskId:input.correlationId,allowed:['NETWORK']});if(remote.record.exitCode!==0)throw new ExecutionFailed('Failed to inspect registered sandbox repository',{stderr:remote.stderr});if(remote.stdout.trim())return {success:true,pushed:false,reason:'REMOTE_NOT_EMPTY'};const push=await this.commands.run({command:'git',args:['push','--set-upstream','origin',input.branch],cwd:input.workspace,taskId:input.correlationId,allowed:['NETWORK']});if(push.record.exitCode!==0)throw new ExecutionFailed('Initial sandbox repository push failed',{stderr:push.stderr});return {success:true,pushed:true,branch:input.branch};}
  async metadata(account:Resource,cwd:string,repository:string,correlationId:string):Promise<GitHubRepositoryMetadata>{assertAccount(account);assertOwnedRepository(account,repository);const result=await this.run(cwd,correlationId,['repo','view',repository,'--json','nameWithOwner,url,isPrivate,defaultBranchRef,viewerPermission']);if(result.exitCode!==0)throw new ExecutionFailed('GitHub repository metadata failed',{stderr:result.stderr});const value=JSON.parse(result.stdout) as {nameWithOwner:string;url:string;isPrivate:boolean;viewerPermission:string;defaultBranchRef?:{name?:string}};return {nameWithOwner:value.nameWithOwner,url:value.url,isPrivate:value.isPrivate,viewerPermission:value.viewerPermission,defaultBranch:value.defaultBranchRef?.name||'main'};}
  async push(repository:Resource,input:{workspace:string;branch:string;correlationId:string}){assertRepository(repository);await this.assertActiveRepositoryOwner(repository,input.workspace,input.correlationId);const result=await this.commands.run({command:'git',args:['push','origin',input.branch],cwd:input.workspace,taskId:input.correlationId,allowed:['NETWORK']});if(result.record.exitCode!==0)throw new ExecutionFailed('Git push failed',{stderr:result.stderr});return {success:true,branch:input.branch};}
  async openPullRequest(repository:Resource,input:{workspace:string;base:string;head:string;title:string;body:string;correlationId:string}){assertRepository(repository);await this.assertActiveRepositoryOwner(repository,input.workspace,input.correlationId);if(!input.head.startsWith('autopilot/'))throw new PolicyViolation('Pull requests may only originate from an autopilot task branch');const existing=await this.run(input.workspace,input.correlationId,['pr','list','--repo',repository.externalReference,'--state','open','--head',input.head,'--base',input.base,'--json','url,number,headRefName,baseRefName','--limit','1']);if(existing.exitCode!==0)throw new ExecutionFailed('Existing pull request lookup failed',{stderr:existing.stderr});const matches=JSON.parse(existing.stdout) as {url:string;number:number;headRefName:string;baseRefName:string}[];if(matches[0])return {success:true,url:matches[0].url,number:matches[0].number,idempotentReplay:true};const result=await this.run(input.workspace,input.correlationId,['pr','create','--repo',repository.externalReference,'--base',input.base,'--head',input.head,'--title',input.title,'--body',input.body]);if(result.exitCode!==0)throw new ExecutionFailed('Pull request creation failed',{stderr:result.stderr});return {success:true,url:result.stdout.trim(),idempotentReplay:false};}
  async setActionsSecret(repository:Resource,input:{workspace:string;name:string;value:string;correlationId:string}){assertRepository(repository);await this.assertActiveRepositoryOwner(repository,input.workspace,input.correlationId);if(!/^[A-Z][A-Z0-9_]{2,127}$/.test(input.name))throw new PolicyViolation('Invalid GitHub Actions secret name');const result=await this.commands.run({command:'gh',args:['secret','set',input.name,'--repo',repository.externalReference],cwd:input.workspace,taskId:input.correlationId,allowed:['NETWORK'],stdin:input.value});if(result.record.exitCode!==0)throw new ExecutionFailed('GitHub Actions secret configuration failed',{stderr:result.stderr});return {success:true,name:input.name};}
  async ciStatus(repository:Resource,input:{workspace:string;branch:string;correlationId:string;wait:boolean;expectedSha?:string}):Promise<GitHubCiStatus>{assertRepository(repository);let found:{databaseId:number;status:string;conclusion:string;url:string;headSha:string}|undefined;for(let attempt=0;attempt<15;attempt++){const list=await this.run(input.workspace,input.correlationId,['run','list','--repo',repository.externalReference,'--branch',input.branch,'--limit','10','--json','databaseId,status,conclusion,url,headSha']);if(list.exitCode!==0)throw new ExecutionFailed('CI status query failed',{stderr:list.stderr});const runs=JSON.parse(list.stdout) as {databaseId:number;status:string;conclusion:string;url:string;headSha:string}[];found=input.expectedSha?runs.find(run=>run.headSha===input.expectedSha):runs[0];if(found)break;await delay(2_000);}if(!found)return {success:false,status:'NOT_FOUND'};if(input.wait&&found.status!=='completed'){const watch=await this.run(input.workspace,input.correlationId,['run','watch',String(found.databaseId),'--repo',repository.externalReference,'--exit-status','--compact']);const refreshed:GitHubCiStatus=await this.ciStatus(repository,{...input,wait:false});return {...refreshed,success:watch.exitCode===0};}return {success:found.status==='completed'&&found.conclusion==='success',...found};}
  async deleteSandboxRepository(repository:Resource,authorization:DestructiveAuthorization,input:{cwd:string;correlationId:string}){assertRepository(repository);await this.assertActiveRepositoryOwner(repository,input.cwd,input.correlationId);if(authorization.resourceId!==repository.resourceId||authorization.confirmation!=='DELETE_SANDBOX_REPOSITORY')throw new PolicyViolation('Explicit DELETE_SANDBOX_REPOSITORY authorization does not match resource');const result=await this.run(input.cwd,input.correlationId,['repo','delete',repository.externalReference,'--yes']);if(result.exitCode!==0){if(/delete_repo|scope|auth/i.test(result.stderr))throw new HumanActionRequired('GitHub requires explicit delete_repo OAuth consent',{officialCommand:'gh auth refresh -s delete_repo'});throw new ExecutionFailed('GitHub repository deletion failed',{stderr:result.stderr});}return {success:true,repository:repository.externalReference};}
  private async assertActiveOwner(account:Resource,cwd:string,correlationId:string){const identity=await this.authenticatedIdentity(cwd,correlationId);if(identity.toLowerCase()!==account.externalReference.toLowerCase())throw new HumanActionRequired('Active GitHub identity does not match the registered sandbox account',{expected:account.externalReference,actual:identity,officialCommand:`gh auth switch --hostname github.com --user ${account.externalReference}`});}
  private async assertActiveRepositoryOwner(repository:Resource,cwd:string,correlationId:string){const [owner]=repository.externalReference.split('/');const identity=await this.authenticatedIdentity(cwd,correlationId);if(identity.toLowerCase()!==owner?.toLowerCase())throw new HumanActionRequired('Active GitHub identity does not own the registered sandbox repository',{expected:owner,actual:identity,officialCommand:`gh auth switch --hostname github.com --user ${owner}`});}
  private async run(cwd:string,id:string,args:string[]){const result=await this.commands.run({command:'gh',args,cwd,taskId:id,allowed:['NETWORK']});return {exitCode:result.record.exitCode,stdout:result.stdout,stderr:result.stderr};}
}
export class UnconfiguredGitHubAdapter {readonly capability='NOT_CONFIGURED';async createSandboxRepository():Promise<never>{throw new UnsupportedOperation('GitHub live adapter is not configured');}}
function assertAccount(resource:Resource){if(resource.type!=='GITHUB_ACCOUNT'||resource.environment!=='SANDBOX'||resource.status!=='ACTIVE'||!resource.permissions.includes('ADMIN'))throw new PolicyViolation('An active SANDBOX GITHUB_ACCOUNT resource with ADMIN permission is required');}
function assertRepository(resource:Resource){if(resource.type!=='GITHUB_REPOSITORY'||resource.environment!=='SANDBOX'||resource.status!=='ACTIVE')throw new PolicyViolation('An active SANDBOX GITHUB_REPOSITORY resource is required');if(!/^[A-Za-z0-9_.-]+\/[A-Za-z0-9_.-]+$/.test(resource.externalReference))throw new PolicyViolation('Registered GitHub repository reference is invalid');}
function assertOwnedRepository(account:Resource,repository:string){const [owner,name,...extra]=repository.split('/');if(extra.length||!owner||!name)throw new PolicyViolation('GitHub repository must use owner/name format');if(owner.toLowerCase()!==account.externalReference.toLowerCase())throw new PolicyViolation('Repository owner differs from registered sandbox account');}
function assertSandboxName(name:string){if(!/^(?:backend-autopilot|autopilot-sandbox)[a-z0-9-]*$/.test(name))throw new PolicyViolation('Sandbox repository name must start with backend-autopilot or autopilot-sandbox');}
function normalizeRemote(value:string){return value.replace(/^git@github\.com:/,'https://github.com/').replace(/\.git$/,'').toLowerCase();}
function delay(ms:number){return new Promise(resolve=>setTimeout(resolve,ms));}
