import { Conflict, ExecutionFailed, HumanActionRequired, PolicyViolation, UnsupportedOperation } from '../../../core/src/errors.js';
import type { CommandRunner } from '../../../execution-engine/src/command-runner.js';
import type { DestructiveAuthorization, Resource } from '../../../schemas/src/index.js';

export interface GitHubRepositoryMetadata {nameWithOwner:string;url:string;isPrivate:boolean;defaultBranch:string;}
export interface GitHubCiStatus {success:boolean;status:string;conclusion?:string;url?:string;databaseId?:number;}
export class LiveGitHubAdapter {
  constructor(private commands:CommandRunner){}
  async authenticatedIdentity(cwd:string,correlationId:string){const result=await this.run(cwd,correlationId,['api','user','--jq','.login']);if(result.exitCode!==0)throw new HumanActionRequired('GitHub login/OAuth is required',{officialCommand:'gh auth login --web --hostname github.com'});return result.stdout.trim();}
  async createSandboxRepository(account:Resource,input:{workspace:string;name:string;description:string;correlationId:string}):Promise<GitHubRepositoryMetadata>{
    assertAccount(account);assertSandboxName(input.name);const identity=await this.authenticatedIdentity(input.workspace,input.correlationId);if(identity.toLowerCase()!==account.externalReference.toLowerCase())throw new HumanActionRequired('Active GitHub identity does not match the explicitly confirmed sandbox account',{expected:account.externalReference,actual:identity,officialCommand:'gh auth switch --hostname github.com --user <sandbox-account>'});const fullName=`${identity}/${input.name}`;const exists=await this.run(input.workspace,input.correlationId,['repo','view',fullName,'--json','nameWithOwner']);if(exists.exitCode===0)throw new Conflict('Refusing to adopt an existing repository during bootstrap',{repository:fullName});const created=await this.run(input.workspace,input.correlationId,['repo','create',fullName,'--private','--source',input.workspace,'--remote','origin','--push','--description',input.description]);if(created.exitCode!==0)throw new ExecutionFailed('GitHub repository creation/push failed',{stderr:created.stderr});return this.metadata(account,input.workspace,fullName,input.correlationId);
  }
  async metadata(account:Resource,cwd:string,repository:string,correlationId:string):Promise<GitHubRepositoryMetadata>{assertAccount(account);assertOwnedSandboxRepository(account,repository);const result=await this.run(cwd,correlationId,['repo','view',repository,'--json','nameWithOwner,url,isPrivate,defaultBranchRef']);if(result.exitCode!==0)throw new ExecutionFailed('GitHub repository metadata failed',{stderr:result.stderr});const value=JSON.parse(result.stdout) as {nameWithOwner:string;url:string;isPrivate:boolean;defaultBranchRef?:{name?:string}};return {nameWithOwner:value.nameWithOwner,url:value.url,isPrivate:value.isPrivate,defaultBranch:value.defaultBranchRef?.name??'main'};}
  async push(repository:Resource,input:{workspace:string;branch:string;correlationId:string}){assertRepository(repository);const result=await this.commands.run({command:'git',args:['push','origin',input.branch],cwd:input.workspace,taskId:input.correlationId,allowed:['NETWORK']});if(result.record.exitCode!==0)throw new ExecutionFailed('Git push failed',{stderr:result.stderr});return {success:true,branch:input.branch};}
  async openPullRequest(repository:Resource,input:{workspace:string;base:string;head:string;title:string;body:string;correlationId:string}){assertRepository(repository);const result=await this.run(input.workspace,input.correlationId,['pr','create','--repo',repository.externalReference,'--base',input.base,'--head',input.head,'--title',input.title,'--body',input.body]);if(result.exitCode!==0)throw new ExecutionFailed('Pull request creation failed',{stderr:result.stderr});return {success:true,url:result.stdout.trim()};}
  async setActionsSecret(repository:Resource,input:{workspace:string;name:string;value:string;correlationId:string}){assertRepository(repository);if(!/^[A-Z][A-Z0-9_]{2,127}$/.test(input.name))throw new PolicyViolation('Invalid GitHub Actions secret name');const result=await this.commands.run({command:'gh',args:['secret','set',input.name,'--repo',repository.externalReference],cwd:input.workspace,taskId:input.correlationId,allowed:['NETWORK'],stdin:input.value});if(result.record.exitCode!==0)throw new ExecutionFailed('GitHub Actions secret configuration failed',{stderr:result.stderr});return {success:true,name:input.name};}
  async ciStatus(repository:Resource,input:{workspace:string;branch:string;correlationId:string;wait:boolean}):Promise<GitHubCiStatus>{assertRepository(repository);let found:{databaseId:number;status:string;conclusion:string;url:string}|undefined;for(let attempt=0;attempt<15;attempt++){const list=await this.run(input.workspace,input.correlationId,['run','list','--repo',repository.externalReference,'--branch',input.branch,'--limit','1','--json','databaseId,status,conclusion,url']);if(list.exitCode!==0)throw new ExecutionFailed('CI status query failed',{stderr:list.stderr});found=(JSON.parse(list.stdout) as {databaseId:number;status:string;conclusion:string;url:string}[])?.[0];if(found)break;await delay(2_000);}if(!found)return {success:false,status:'NOT_FOUND'};if(input.wait&&found.status!=='completed'){const watch=await this.run(input.workspace,input.correlationId,['run','watch',String(found.databaseId),'--repo',repository.externalReference,'--exit-status','--compact']);const refreshed:GitHubCiStatus=await this.ciStatus(repository,{...input,wait:false});return {...refreshed,success:watch.exitCode===0};}return {success:found.status==='completed'&&found.conclusion==='success',...found};}
  async deleteSandboxRepository(repository:Resource,authorization:DestructiveAuthorization,input:{cwd:string;correlationId:string}){assertRepository(repository);if(authorization.resourceId!==repository.resourceId||authorization.confirmation!=='DELETE_SANDBOX_REPOSITORY')throw new PolicyViolation('Explicit DELETE_SANDBOX_REPOSITORY authorization does not match resource');const result=await this.run(input.cwd,input.correlationId,['repo','delete',repository.externalReference,'--yes']);if(result.exitCode!==0){if(/delete_repo|scope|auth/i.test(result.stderr))throw new HumanActionRequired('GitHub requires explicit delete_repo OAuth consent',{officialCommand:'gh auth refresh -s delete_repo'});throw new ExecutionFailed('GitHub repository deletion failed',{stderr:result.stderr});}return {success:true,repository:repository.externalReference};}
  private async run(cwd:string,id:string,args:string[]){const result=await this.commands.run({command:'gh',args,cwd,taskId:id,allowed:['NETWORK']});return {exitCode:result.record.exitCode,stdout:result.stdout,stderr:result.stderr};}
}
export class UnconfiguredGitHubAdapter {readonly capability='NOT_CONFIGURED';async createSandboxRepository():Promise<never>{throw new UnsupportedOperation('GitHub live adapter is not configured');}}
function assertAccount(resource:Resource){if(resource.type!=='GITHUB_ACCOUNT'||resource.environment!=='SANDBOX'||resource.status!=='ACTIVE'||!resource.permissions.includes('ADMIN'))throw new PolicyViolation('An active SANDBOX GITHUB_ACCOUNT resource with ADMIN permission is required');}
function assertRepository(resource:Resource){if(resource.type!=='GITHUB_REPOSITORY'||resource.environment!=='SANDBOX'||resource.status!=='ACTIVE')throw new PolicyViolation('An active SANDBOX GITHUB_REPOSITORY resource is required');const [,name]=resource.externalReference.split('/');assertSandboxName(name??'');}
function assertOwnedSandboxRepository(account:Resource,repository:string){const [owner,name]=repository.split('/');if(owner?.toLowerCase()!==account.externalReference.toLowerCase())throw new PolicyViolation('Repository owner differs from registered sandbox account');assertSandboxName(name??'');}
function assertSandboxName(name:string){if(!/^(?:backend-autopilot|autopilot-sandbox)[a-z0-9-]*$/.test(name))throw new PolicyViolation('Sandbox repository name must start with backend-autopilot or autopilot-sandbox');}
function delay(ms:number){return new Promise(resolve=>setTimeout(resolve,ms));}
