import { createHash } from 'node:crypto';
import { Pool } from 'pg';
import { ArchitectureViolation, ExecutionFailed, PolicyViolation } from '../../../core/src/errors.js';
import type { SecretProvider } from '../../../core/src/secrets.js';
import type { Resource } from '../../../schemas/src/index.js';

export interface MigrationInput {name:string;sql:string;rollback:string;}
export interface MigrationResult {name:string;checksum:string;status:'APPLIED'|'ALREADY_APPLIED';appliedAt:string;}
export interface DatabaseAdapter {health(resource:Resource):Promise<{connected:boolean;provider:string}>;applyMigrations(resource:Resource,migrations:MigrationInput[]):Promise<MigrationResult[]>;inspectSchema(resource:Resource):Promise<unknown>;enableRls(resource:Resource,table:string):Promise<void>;createOwnershipPolicy(resource:Resource,input:{table:string;ownerColumn:string;policyName:string;dialect:'SUPABASE'|'POSTGRES_JWT'}):Promise<void>;}

export class ExternalPostgresAdapter implements DatabaseAdapter {
  constructor(private secrets:SecretProvider){}
  async health(resource:Resource){return this.withPool(resource,async pool=>{await pool.query('select 1');return {connected:true,provider:resource.provider};});}
  async applyMigrations(resource:Resource,migrations:MigrationInput[]){assertDatabase(resource,'MIGRATE');for(const migration of migrations)validateMigration(migration);return this.withPool(resource,async pool=>{const client=await pool.connect();try{await client.query('begin');await client.query("select pg_advisory_xact_lock(hashtext('backend-autopilot-migrations'))");await client.query('create table if not exists _autopilot_migrations (name text primary key, checksum text not null, rollback text not null, applied_at timestamptz not null default now())');const results:MigrationResult[]=[];for(const migration of migrations){const checksum=createHash('sha256').update(migration.sql).digest('hex');const existing=await client.query<{checksum:string;applied_at:Date}>('select checksum, applied_at from _autopilot_migrations where name=$1',[migration.name]);if(existing.rows[0]){if(existing.rows[0].checksum!==checksum)throw new ArchitectureViolation('Applied migration checksum differs from requested migration',{name:migration.name});results.push({name:migration.name,checksum,status:'ALREADY_APPLIED',appliedAt:existing.rows[0].applied_at.toISOString()});continue;}await client.query(migration.sql);const inserted=await client.query<{applied_at:Date}>('insert into _autopilot_migrations(name,checksum,rollback) values($1,$2,$3) returning applied_at',[migration.name,checksum,migration.rollback]);results.push({name:migration.name,checksum,status:'APPLIED',appliedAt:inserted.rows[0]!.applied_at.toISOString()});}await client.query('commit');return results;}catch(error){await client.query('rollback');throw error;}finally{client.release();}});}
  async inspectSchema(resource:Resource){assertDatabase(resource,'READ');return this.withPool(resource,async pool=>{const [columns,tables,indexes,policies,functions]=await Promise.all([pool.query<{table_schema:string;table_name:string;column_name:string;data_type:string;is_nullable:string}>("select table_schema,table_name,column_name,data_type,is_nullable from information_schema.columns where table_schema not in ('pg_catalog','information_schema') order by table_schema,table_name,ordinal_position"),pool.query<{table_schema:string;table_name:string;table_type:string}>("select table_schema,table_name,table_type from information_schema.tables where table_schema not in ('pg_catalog','information_schema') order by table_schema,table_name"),pool.query<{schemaname:string;tablename:string;indexname:string;indexdef:string}>("select schemaname,tablename,indexname,indexdef from pg_indexes where schemaname not in ('pg_catalog','information_schema') order by schemaname,tablename,indexname"),pool.query<{schemaname:string;tablename:string;policyname:string;cmd:string;qual:string|null;with_check:string|null}>("select schemaname,tablename,policyname,cmd,qual,with_check from pg_policies order by schemaname,tablename,policyname"),pool.query<{routine_schema:string;routine_name:string;routine_type:string}>("select routine_schema,routine_name,routine_type from information_schema.routines where routine_schema not in ('pg_catalog','information_schema') order by routine_schema,routine_name")]);return {provider:resource.provider,tables:tables.rows,columns:columns.rows,indexes:indexes.rows,policies:policies.rows,functions:functions.rows};});}
  async enableRls(resource:Resource,table:string){assertDatabase(resource,'MIGRATE');const name=identifier(table);await this.withPool(resource,async pool=>{await pool.query(`alter table ${name} enable row level security`);});}
  async createOwnershipPolicy(resource:Resource,input:{table:string;ownerColumn:string;policyName:string;dialect:'SUPABASE'|'POSTGRES_JWT'}){assertDatabase(resource,'MIGRATE');const table=identifier(input.table),column=identifier(input.ownerColumn),policy=identifier(input.policyName);const principal=input.dialect==='SUPABASE'?'auth.uid()':"nullif(current_setting('request.jwt.claim.sub', true), '')::uuid";await this.withPool(resource,async pool=>{await pool.query(`drop policy if exists ${policy} on ${table}`);await pool.query(`create policy ${policy} on ${table} for all using (${column} = ${principal}) with check (${column} = ${principal})`);});}
  private async withPool<T>(resource:Resource,fn:(pool:Pool)=>Promise<T>){const reference=resource.secretRefs[0];if(!reference)throw new PolicyViolation('Database resource has no connection secret reference');const connectionString=await this.secrets.get(reference,resource.projectId);const pool=new Pool({connectionString,connectionTimeoutMillis:10_000,max:2});try{return await fn(pool);}catch(error){if(error instanceof ArchitectureViolation||error instanceof PolicyViolation)throw error;throw new ExecutionFailed('External PostgreSQL operation failed',{provider:resource.provider,cause:error instanceof Error?error.message:'unknown'});}finally{await pool.end();}}
}
function assertDatabase(resource:Resource,permission:'READ'|'MIGRATE'){if(resource.type!=='DATABASE'||resource.environment==='PRODUCTION'||resource.status!=='ACTIVE'||!resource.permissions.includes(permission))throw new PolicyViolation(`Active non-production DATABASE resource with ${permission} permission required`);}
function validateMigration(migration:MigrationInput){if(!/^[a-z0-9][a-z0-9_-]{2,127}$/.test(migration.name))throw new ArchitectureViolation('Invalid migration name');if(!migration.rollback.trim())throw new ArchitectureViolation('Migration rollback information is required');if(/\b(drop\s+database|alter\s+system|copy\b[\s\S]*\bprogram|pg_terminate_backend|truncate\s+table|drop\s+schema\b[\s\S]*\bcascade|create\s+(?:user|role)[\s\S]*password)\b/i.test(migration.sql)||/(?:gh[pousr]_|sbp_)[A-Za-z0-9_-]+/.test(migration.sql))throw new ArchitectureViolation('Migration contains a prohibited destructive or credential-bearing statement');}
function identifier(value:string){if(!/^[a-z_][a-z0-9_]{0,62}$/.test(value))throw new ArchitectureViolation('Unsafe SQL identifier',{value});return `"${value}"`;}
