import { mkdir, readFile, rename, writeFile } from 'node:fs/promises';
import { dirname, join } from 'node:path';
import type { CanonicalPromotionRequest, StateStore } from '../../core/src/ports.js';
import type { AdminOperation, Artifact, AuditEvent, CanonicalDevelopmentRepository, ConsoleScreen, ExecutionJob, Operator, Project, ProjectContext, ProjectMembership, Resource, Run, SystemSetting, Task, Transition } from '../../schemas/src/index.js';
import { MemoryStateStore } from './memory-store.js';

interface Snapshot {projects:Project[];resources:Resource[];contexts:ProjectContext[];tasks:Task[];artifacts:Artifact[];runs:Run[];jobs?:ExecutionJob[];transitions:Transition[];audit:AuditEvent[];settings?:SystemSetting[];screens?:ConsoleScreen[];operators?:Operator[];memberships?:ProjectMembership[];operations?:AdminOperation[];canonicalRepositories?:CanonicalDevelopmentRepository[];}
export class FileStateStore implements StateStore {
  private memory=new MemoryStateStore();private ready:Promise<void>;private writeQueue=Promise.resolve();
  constructor(private path=join(process.cwd(),'.autopilot','state.json')){this.ready=this.load();}
  private async load(){try{const data=JSON.parse(await readFile(this.path,'utf8')) as Snapshot;for(const v of data.projects)await this.memory.createProject(v);for(const v of data.resources)await this.memory.createResource(v);for(const v of data.contexts)await this.memory.saveContext(v);for(const v of data.tasks)await this.memory.createTask(v);for(const v of data.artifacts)await this.memory.saveArtifact(v);for(const v of data.runs)await this.memory.saveRun(v);for(const v of data.jobs??[])await this.memory.createExecutionJob(v);for(const v of data.transitions)await this.memory.appendTransition(v);for(const v of data.audit)await this.memory.appendAudit(v);for(const v of data.settings??[])await this.memory.upsertSystemSetting(v);for(const v of data.screens??[])await this.memory.upsertConsoleScreen(v);for(const v of data.operators??[])await this.memory.upsertOperator(v);for(const v of data.memberships??[])await this.memory.upsertMembership(v);for(const v of data.operations??[])await this.memory.saveAdminOperation(v);for(const v of data.canonicalRepositories??[])await this.memory.seedCanonicalRepository(v);}catch(error){if((error as NodeJS.ErrnoException).code!=='ENOENT')throw error;}}
  private async persist(){this.writeQueue=this.writeQueue.then(async()=>{const projects=await this.memory.listProjects();const resources=(await Promise.all(projects.map(p=>this.memory.listResources(p.id)))).flat();const contexts=(await Promise.all(projects.map(p=>this.memory.listContexts(p.id)))).flat();const tasks=(await Promise.all(projects.map(p=>this.memory.listTasks(p.id)))).flat();const artifacts=(await Promise.all(projects.map(p=>this.memory.listArtifacts(p.id)))).flat();const runs=(await Promise.all(projects.map(p=>this.memory.listRuns(p.id)))).flat();const jobs=(await Promise.all(projects.map(p=>this.memory.listExecutionJobs(p.id)))).flat();const transitions=(await Promise.all(tasks.map(t=>this.memory.listTransitions(t.id)))).flat();const audit=(await Promise.all(projects.map(p=>this.memory.listAudit(p.id)))).flat();const settings=await this.memory.listSystemSettings(),screens=await this.memory.listConsoleScreens(),operators=await this.memory.listOperators(),memberships=await this.memory.listMemberships(),operations=await this.memory.listAdminOperations();const canonicalRepositories=(await Promise.all(projects.map(p=>this.memory.listCanonicalRepositories(p.id)))).flat();const snapshot:Snapshot={projects,resources,contexts,tasks,artifacts,runs,jobs,transitions,audit,settings,screens,operators,memberships,operations,canonicalRepositories};await mkdir(dirname(this.path),{recursive:true});const temp=`${this.path}.${crypto.randomUUID()}.tmp`;await writeFile(temp,JSON.stringify(snapshot,null,2),'utf8');await rename(temp,this.path);});await this.writeQueue;}
  async createProject(v:Project){await this.ready;const r=await this.memory.createProject(v);await this.persist();return r;}async getProject(id:string){await this.ready;return this.memory.getProject(id);}async listProjects(){await this.ready;return this.memory.listProjects();}
  async updateProject(v:Project){await this.ready;const r=await this.memory.updateProject(v);await this.persist();return r;}
  async createResource(v:Resource){await this.ready;const r=await this.memory.createResource(v);await this.persist();return r;}async updateResource(v:Resource){await this.ready;const r=await this.memory.updateResource(v);await this.persist();return r;}async getResource(id:string){await this.ready;return this.memory.getResource(id);}async findResource(p:string,e:string){await this.ready;return this.memory.findResource(p,e);}async listResources(p:string){await this.ready;return this.memory.listResources(p);}
  async saveContext(v:ProjectContext){await this.ready;const r=await this.memory.saveContext(v);await this.persist();return r;}async updateContext(v:ProjectContext){await this.ready;const r=await this.memory.updateContext(v);await this.persist();return r;}async getContext(p:string,id:string){await this.ready;return this.memory.getContext(p,id);}async getLatestContext(p:string){await this.ready;return this.memory.getLatestContext(p);}async listContexts(p:string){await this.ready;return this.memory.listContexts(p);}
  async createTask(v:Task){await this.ready;const r=await this.memory.createTask(v);await this.persist();return r;}async updateTask(v:Task){await this.ready;const r=await this.memory.updateTask(v);await this.persist();return r;}async getTask(p:string,t:string){await this.ready;return this.memory.getTask(p,t);}async listTasks(p:string){await this.ready;return this.memory.listTasks(p);}
  async saveArtifact(v:Artifact){await this.ready;const r=await this.memory.saveArtifact(v);await this.persist();return r;}async updateArtifact(v:Artifact){await this.ready;const r=await this.memory.updateArtifact(v);await this.persist();return r;}async getArtifact(p:string,id:string){await this.ready;return this.memory.getArtifact(p,id);}async listArtifacts(p:string,t?:string){await this.ready;return this.memory.listArtifacts(p,t);}
  async saveRun(v:Run){await this.ready;const r=await this.memory.saveRun(v);await this.persist();return r;}async updateRun(v:Run){await this.ready;const r=await this.memory.updateRun(v);await this.persist();return r;}async getRun(p:string,id:string){await this.ready;return this.memory.getRun(p,id);}async findRunByOperation(p:string,o:string){await this.ready;return this.memory.findRunByOperation(p,o);}async listRuns(p:string,t?:string){await this.ready;return this.memory.listRuns(p,t);}
  async createExecutionJob(v:ExecutionJob){await this.ready;const r=await this.memory.createExecutionJob(v);await this.persist();return r;}async updateExecutionJob(v:ExecutionJob){await this.ready;const r=await this.memory.updateExecutionJob(v);await this.persist();return r;}async getExecutionJob(p:string,id:string){await this.ready;return this.memory.getExecutionJob(p,id);}async getExecutionJobById(id:string){await this.ready;return this.memory.getExecutionJobById(id);}async findExecutionJobByOperation(p:string,o:string){await this.ready;return this.memory.findExecutionJobByOperation(p,o);}async listExecutionJobs(p:string,t?:string){await this.ready;return this.memory.listExecutionJobs(p,t);}async claimExecutionJob(p:string,id:string,owner:string,expires:string,now:string){await this.ready;const r=await this.memory.claimExecutionJob(p,id,owner,expires,now);if(r)await this.persist();return r;}
  async transitionTask(task:Task,transition:Transition){await this.ready;const r=await this.memory.transitionTask(task,transition);await this.persist();return r;}
  async appendTransition(v:Transition){await this.ready;await this.memory.appendTransition(v);await this.persist();}async listTransitions(t:string){await this.ready;return this.memory.listTransitions(t);}
  async appendAudit(v:AuditEvent){await this.ready;await this.memory.appendAudit(v);await this.persist();}async getAudit(p:string,id:string){await this.ready;return this.memory.getAudit(p,id);}async listAudit(p:string){await this.ready;return this.memory.listAudit(p);}
  async upsertSystemSetting(v:SystemSetting){await this.ready;const r=await this.memory.upsertSystemSetting(v);await this.persist();return r;}async getSystemSetting(k:string){await this.ready;return this.memory.getSystemSetting(k);}async listSystemSettings(){await this.ready;return this.memory.listSystemSettings();}async deleteSystemSetting(k:string){await this.ready;await this.memory.deleteSystemSetting(k);await this.persist();}
  async upsertConsoleScreen(v:ConsoleScreen){await this.ready;const r=await this.memory.upsertConsoleScreen(v);await this.persist();return r;}async getConsoleScreen(id:string){await this.ready;return this.memory.getConsoleScreen(id);}async listConsoleScreens(){await this.ready;return this.memory.listConsoleScreens();}async deleteConsoleScreen(id:string){await this.ready;await this.memory.deleteConsoleScreen(id);await this.persist();}
  async upsertOperator(v:Operator){await this.ready;const r=await this.memory.upsertOperator(v);await this.persist();return r;}async getOperator(id:string){await this.ready;return this.memory.getOperator(id);}async listOperators(){await this.ready;return this.memory.listOperators();}async deleteOperator(id:string){await this.ready;await this.memory.deleteOperator(id);await this.persist();}
  async upsertMembership(v:ProjectMembership){await this.ready;const r=await this.memory.upsertMembership(v);await this.persist();return r;}async getMembership(u:string,p:string){await this.ready;return this.memory.getMembership(u,p);}async listMemberships(p?:string,u?:string){await this.ready;return this.memory.listMemberships(p,u);}async deleteMembership(u:string,p:string){await this.ready;await this.memory.deleteMembership(u,p);await this.persist();}
  async saveAdminOperation(v:AdminOperation){await this.ready;const r=await this.memory.saveAdminOperation(v);await this.persist();return r;}async getAdminOperation(id:string){await this.ready;return this.memory.getAdminOperation(id);}async listAdminOperations(){await this.ready;return this.memory.listAdminOperations();}async listMigrationMarkers(){return [];}
  async getCanonicalRepository(p:string,id:string){await this.ready;return this.memory.getCanonicalRepository(p,id);}async getActiveCanonicalRepository(p:string){await this.ready;return this.memory.getActiveCanonicalRepository(p);}async listCanonicalRepositories(p:string){await this.ready;return this.memory.listCanonicalRepositories(p);}
  async promoteCanonicalRepository(request:CanonicalPromotionRequest){await this.ready;const r=await this.memory.promoteCanonicalRepository(request);await this.persist();return r;}
}
