import { index, jsonb, pgTable, text, timestamp, uniqueIndex, uuid } from 'drizzle-orm/pg-core';

export const projects=pgTable('projects',{id:uuid('id').primaryKey(),slug:text('slug').notNull(),data:jsonb('data').notNull(),createdAt:timestamp('created_at',{withTimezone:true}).notNull()},t=>[uniqueIndex('projects_slug_uq').on(t.slug)]);
export const resources=pgTable('resources',{id:uuid('id').primaryKey(),projectId:uuid('project_id').notNull(),provider:text('provider').notNull(),externalReference:text('external_reference').notNull(),data:jsonb('data').notNull(),createdAt:timestamp('created_at',{withTimezone:true}).notNull()},t=>[uniqueIndex('resources_external_uq').on(t.provider,t.externalReference),index('resources_project_idx').on(t.projectId)]);
export const contexts=pgTable('project_contexts',{id:uuid('id').primaryKey(),projectId:uuid('project_id').notNull(),data:jsonb('data').notNull(),createdAt:timestamp('created_at',{withTimezone:true}).notNull()},t=>[index('contexts_project_idx').on(t.projectId)]);
export const tasks=pgTable('tasks',{id:uuid('id').primaryKey(),projectId:uuid('project_id').notNull(),externalKey:text('external_key').notNull(),data:jsonb('data').notNull(),createdAt:timestamp('created_at',{withTimezone:true}).notNull()},t=>[uniqueIndex('tasks_external_uq').on(t.projectId,t.externalKey),index('tasks_project_idx').on(t.projectId)]);
export const artifacts=pgTable('artifacts',{id:uuid('id').primaryKey(),projectId:uuid('project_id').notNull(),taskId:uuid('task_id'),data:jsonb('data').notNull(),createdAt:timestamp('created_at',{withTimezone:true}).notNull()},t=>[index('artifacts_project_idx').on(t.projectId),index('artifacts_task_idx').on(t.taskId)]);
export const runs=pgTable('runs',{id:uuid('id').primaryKey(),projectId:uuid('project_id').notNull(),taskId:uuid('task_id').notNull(),operationId:text('operation_id').notNull(),data:jsonb('data').notNull(),createdAt:timestamp('created_at',{withTimezone:true}).notNull()},t=>[uniqueIndex('runs_operation_uq').on(t.projectId,t.operationId),index('runs_task_idx').on(t.taskId)]);
export const transitions=pgTable('task_transitions',{id:uuid('id').primaryKey(),taskId:uuid('task_id').notNull(),data:jsonb('data').notNull(),createdAt:timestamp('created_at',{withTimezone:true}).notNull()},t=>[index('transitions_task_idx').on(t.taskId)]);
export const auditEvents=pgTable('audit_events',{id:uuid('id').primaryKey(),projectId:uuid('project_id').notNull(),data:jsonb('data').notNull(),createdAt:timestamp('created_at',{withTimezone:true}).notNull()},t=>[index('audit_project_idx').on(t.projectId)]);
