import { bigint, index, integer, jsonb, pgTable, text, timestamp, uniqueIndex, uuid } from 'drizzle-orm/pg-core';

export const projects=pgTable('projects',{id:uuid('id').primaryKey(),slug:text('slug').notNull(),data:jsonb('data').notNull(),createdAt:timestamp('created_at',{withTimezone:true}).notNull()},t=>[uniqueIndex('projects_slug_uq').on(t.slug)]);
export const resources=pgTable('resources',{id:uuid('id').primaryKey(),projectId:uuid('project_id').notNull(),provider:text('provider').notNull(),externalReference:text('external_reference').notNull(),data:jsonb('data').notNull(),createdAt:timestamp('created_at',{withTimezone:true}).notNull()},t=>[uniqueIndex('resources_external_uq').on(t.provider,t.externalReference),index('resources_project_idx').on(t.projectId)]);
export const contexts=pgTable('project_contexts',{id:uuid('id').primaryKey(),projectId:uuid('project_id').notNull(),data:jsonb('data').notNull(),createdAt:timestamp('created_at',{withTimezone:true}).notNull()},t=>[index('contexts_project_idx').on(t.projectId)]);
export const tasks=pgTable('tasks',{id:uuid('id').primaryKey(),projectId:uuid('project_id').notNull(),externalKey:text('external_key').notNull(),data:jsonb('data').notNull(),createdAt:timestamp('created_at',{withTimezone:true}).notNull()},t=>[uniqueIndex('tasks_external_uq').on(t.projectId,t.externalKey),index('tasks_project_idx').on(t.projectId)]);
export const artifacts=pgTable('artifacts',{id:uuid('id').primaryKey(),projectId:uuid('project_id').notNull(),taskId:uuid('task_id'),runId:uuid('run_id'),kind:text('kind'),status:text('status').notNull().default('AVAILABLE'),contentHash:text('content_hash'),storageBucket:text('storage_bucket'),storagePath:text('storage_path'),byteSize:bigint('byte_size',{mode:'number'}),data:jsonb('data').notNull(),createdAt:timestamp('created_at',{withTimezone:true}).notNull()},t=>[index('artifacts_project_idx').on(t.projectId),index('artifacts_task_idx').on(t.taskId)]);
export const runs=pgTable('runs',{id:uuid('id').primaryKey(),projectId:uuid('project_id').notNull(),taskId:uuid('task_id').notNull(),operationId:text('operation_id').notNull(),data:jsonb('data').notNull(),createdAt:timestamp('created_at',{withTimezone:true}).notNull()},t=>[uniqueIndex('runs_operation_uq').on(t.projectId,t.operationId),index('runs_task_idx').on(t.taskId)]);
export const executionJobs=pgTable('execution_jobs',{
  id:uuid('id').primaryKey(),projectId:uuid('project_id').notNull(),taskId:uuid('task_id').notNull(),resourceId:uuid('resource_id').notNull(),runId:uuid('run_id'),operationId:text('operation_id').notNull(),kind:text('kind').notNull(),status:text('status').notNull(),attempt:integer('attempt').notNull(),workflowRunId:text('workflow_run_id'),leaseOwner:text('lease_owner'),leaseExpiresAt:timestamp('lease_expires_at',{withTimezone:true}),data:jsonb('data').notNull(),createdAt:timestamp('created_at',{withTimezone:true}).notNull(),updatedAt:timestamp('updated_at',{withTimezone:true}).notNull()
},t=>[uniqueIndex('execution_jobs_operation_uq').on(t.projectId,t.operationId),index('execution_jobs_task_idx').on(t.taskId),index('execution_jobs_status_idx').on(t.status),index('execution_jobs_lease_idx').on(t.leaseExpiresAt)]);
export const transitions=pgTable('task_transitions',{id:uuid('id').primaryKey(),taskId:uuid('task_id').notNull(),data:jsonb('data').notNull(),createdAt:timestamp('created_at',{withTimezone:true}).notNull()},t=>[index('transitions_task_idx').on(t.taskId)]);
export const auditEvents=pgTable('audit_events',{id:uuid('id').primaryKey(),projectId:uuid('project_id').notNull(),data:jsonb('data').notNull(),createdAt:timestamp('created_at',{withTimezone:true}).notNull()},t=>[index('audit_project_idx').on(t.projectId)]);
export const migrationMarkers=pgTable('migration_markers',{key:text('key').primaryKey(),checksum:text('checksum').notNull(),data:jsonb('data').notNull(),createdAt:timestamp('created_at',{withTimezone:true}).notNull()});
export const systemSettings=pgTable('system_settings',{key:text('key').primaryKey(),data:jsonb('data').notNull(),updatedAt:timestamp('updated_at',{withTimezone:true}).notNull()});
export const consoleScreens=pgTable('console_screens',{screenId:text('screen_id').primaryKey(),data:jsonb('data').notNull(),updatedAt:timestamp('updated_at',{withTimezone:true}).notNull()});
export const adminOperations=pgTable('admin_operations',{operationId:text('operation_id').primaryKey(),actor:text('actor').notNull(),tool:text('tool').notNull(),projectId:uuid('project_id'),data:jsonb('data').notNull(),createdAt:timestamp('created_at',{withTimezone:true}).notNull()},t=>[index('admin_operations_project_idx').on(t.projectId)]);
