import { randomBytes } from 'node:crypto';
import { resolve } from 'node:path';
import { ExecutionFailed, HumanActionRequired, PolicyViolation, UnsupportedOperation } from '../../../core/src/errors.js';
import type { MutableSecretProvider, SecretProvider } from '../../../core/src/secrets.js';
import type { CommandRunner } from '../../../execution-engine/src/command-runner.js';
import type { DestructiveAuthorization, Resource } from '../../../schemas/src/index.js';
export * from './artifact-storage.js';

export interface SupabaseProjectResult {ref:string;name:string;organizationId:string;region:string;status:string;databaseSecretRef:string;passwordSecretRef:string;}
export interface ExistingSupabaseProject {ref:string;name:string;organizationId:string;region:string;status:string;}
export class LiveSupabaseCliAdapter {
  constructor(private commands:CommandRunner,private secrets:MutableSecretProvider){}
  async discoverOrganizations(input:{cwd:string;projectId:string;confirmedDedicatedSandbox:boolean}){if(!input.confirmedDedicatedSandbox)throw new HumanActionRequired('Confirm that the active Supabase session belongs to a dedicated sandbox account before organization discovery');const result=await this.run(input.cwd,input.projectId,['orgs','list','--output','json']);if(result.exitCode!==0)throw new HumanActionRequired('Official Supabase login/OAuth is required',{officialCommand:'supabase login'});const organizations=JSON.parse(result.stdout) as {id:string;name:string}[];if(organizations.length!==1)throw new HumanActionRequired('Sandbox account must expose exactly one unambiguous organization or an organization ID must be explicitly selected',{organizationCount:organizations.length});return organizations[0]!;}
  async discoverExistingProject(organization:Resource,input:{cwd:string;expectedRef:string;correlationId:string}):Promise<ExistingSupabaseProject>{assertOrganization(organization);if(!/^[a-z]{20}$/.test(input.expectedRef))throw new PolicyViolation('Invalid expected Supabase project ref');const result=await this.run(input.cwd,input.correlationId,['projects','list','--output','json']);if(result.exitCode!==0)throw new HumanActionRequired('Official Supabase login/OAuth is required',{officialCommand:'supabase login'});const projects=JSON.parse(result.stdout) as {id?:string;ref?:string;name:string;organization_id:string;region:string;status:string}[];const matches=projects.filter(project=>(project.ref??project.id)===input.expectedRef&&project.organization_id===organization.externalReference);if(projects.length!==1||matches.length!==1)throw new HumanActionRequired('Dedicated sandbox account must expose exactly the explicitly confirmed single project',{projectCount:projects.length,expectedRef:input.expectedRef,matchingProjects:matches.length});const project=matches[0]!;return {ref:project.ref??project.id!,name:project.name,organizationId:project.organization_id,region:project.region,status:project.status};}
  async createSandboxProject(organization:Resource,input:{cwd:string;name:string;region:string;secretPrefix:string;correlationId:string}):Promise<SupabaseProjectResult>{assertOrganization(organization);assertSandboxName(input.name);const password=randomBytes(30).toString('base64url');const passwordRef=`${input.secretPrefix}_DB_PASSWORD`;const databaseRef=`${input.secretPrefix}_DATABASE_URL`;await this.secrets.set(passwordRef,password,organization.projectId);const args=['projects','create',input.name,'--org-id',organization.externalReference,'--db-password',password,'--region',input.region,'--output','json','--yes'];const result=await this.commands.run({command:'supabase',args,cwd:input.cwd,taskId:input.correlationId,allowed:['NETWORK'],sensitiveArgIndexes:[6],env:supabaseEnvironment()});if(result.record.exitCode!==0){await this.secrets.revoke(passwordRef,organization.projectId);if(/access token|login|unauthorized|forbidden/i.test(result.stderr))throw new HumanActionRequired('Official Supabase login/OAuth is required',{officialCommand:'supabase login'});throw new ExecutionFailed('Supabase project creation failed',{stderr:result.stderr});}const created=JSON.parse(result.stdout) as {ref?:string;id?:string;name?:string;organization_id?:string;region?:string;status?:string};const ref=created.ref??created.id;if(!ref)throw new ExecutionFailed('Supabase create response did not contain a project reference');const url=`postgresql://postgres:${encodeURIComponent(password)}@db.${ref}.supabase.co:5432/postgres?sslmode=require`;await this.secrets.set(databaseRef,url,organization.projectId);return {ref,name:created.name??input.name,organizationId:created.organization_id??organization.externalReference,region:created.region??input.region,status:created.status??'UNKNOWN',databaseSecretRef:databaseRef,passwordSecretRef:passwordRef};}
  async deleteSandboxProject(project:Resource,authorization:DestructiveAuthorization,input:{cwd:string;correlationId:string}){assertProject(project);if(authorization.resourceId!==project.resourceId||authorization.confirmation!=='DELETE_SANDBOX_DATABASE')throw new PolicyViolation('Explicit DELETE_SANDBOX_DATABASE authorization does not match resource');const result=await this.run(input.cwd,input.correlationId,['projects','delete',project.externalReference,'--yes']);if(result.exitCode!==0)throw new ExecutionFailed('Supabase project deletion failed',{stderr:result.stderr});return {success:true,ref:project.externalReference};}
  private async run(cwd:string,id:string,args:string[]){const result=await this.commands.run({command:'supabase',args,cwd,taskId:id,allowed:['NETWORK','MIGRATION'],env:supabaseEnvironment()});return {exitCode:result.record.exitCode,stdout:result.stdout,stderr:result.stderr};}
}

export class SupabaseManagementApiAdapter {
  constructor(private secrets:SecretProvider,public readonly tokenReference='SUPABASE_ACCESS_TOKEN',private baseUrl='https://api.supabase.com/v1'){}
  async health(project:Resource){assertProject(project);return this.request('GET',`/projects/${encodeURIComponent(project.externalReference)}`,undefined,project.projectId);}
  async updateAuth(project:Resource,config:{site_url?:string;disable_signup?:boolean;jwt_exp?:number;mailer_autoconfirm?:boolean}){assertProject(project);return this.request('PATCH',`/projects/${encodeURIComponent(project.externalReference)}/config/auth`,config,project.projectId);}
  async updateStorage(project:Resource,config:{fileSizeLimit?:number;features?:Record<string,unknown>}){assertProject(project);return this.request('PATCH',`/projects/${encodeURIComponent(project.externalReference)}/config/storage`,config,project.projectId);}
  async listStorageBuckets(project:Resource){assertProject(project);return this.request('GET',`/projects/${encodeURIComponent(project.externalReference)}/storage/buckets`,undefined,project.projectId);}
  async configureDatabaseCredential(project:Resource,secretPrefix:string){assertProject(project);if(!/^[A-Z][A-Z0-9_]{2,96}$/.test(secretPrefix))throw new PolicyViolation('Invalid sandbox database secret prefix');const password=randomBytes(30).toString('base64url');const passwordRef=`${secretPrefix}_DB_PASSWORD`;if(!('set' in this.secrets))throw new UnsupportedOperation('Mutable secret provider is required to configure database credentials');await (this.secrets as MutableSecretProvider).set(passwordRef,password,project.projectId);try{await this.request('PATCH',`/projects/${encodeURIComponent(project.externalReference)}/database/password`,{password},project.projectId);return this.refreshDatabaseConnection(project,secretPrefix);}catch(error){if('revoke' in this.secrets)await (this.secrets as MutableSecretProvider).revoke(passwordRef,project.projectId);throw error;}}
  async refreshDatabaseConnection(project:Resource,secretPrefix:string){assertProject(project);if(!/^[A-Z][A-Z0-9_]{2,96}$/.test(secretPrefix))throw new PolicyViolation('Invalid sandbox database secret prefix');if(!('set' in this.secrets))throw new UnsupportedOperation('Mutable secret provider is required to configure database credentials');const passwordRef=`${secretPrefix}_DB_PASSWORD`;const databaseRef=`${secretPrefix}_DATABASE_URL`;const password=await this.secrets.get(passwordRef,project.projectId);const configs=await this.request('GET',`/projects/${encodeURIComponent(project.externalReference)}/config/database/pooler`,undefined,project.projectId) as {database_type?:string;db_user?:string;db_host?:string;db_port?:number;db_name?:string}[];const primary=configs.find(config=>config.database_type==='PRIMARY')??configs[0];if(!primary?.db_user||!primary.db_host||!primary.db_host.endsWith('.pooler.supabase.com')||!primary.db_user.endsWith(`.${project.externalReference}`))throw new ExecutionFailed('Supabase pooler metadata did not match the registered project');const url=`postgresql://${encodeURIComponent(primary.db_user)}:${encodeURIComponent(password)}@${primary.db_host}:5432/${encodeURIComponent(primary.db_name??'postgres')}?uselibpqcompat=true&sslmode=require`;await (this.secrets as MutableSecretProvider).set(databaseRef,url,project.projectId);return {accessTokenSecretRef:this.tokenReference,passwordSecretRef:passwordRef,databaseSecretRef:databaseRef};}
  private async request(method:string,path:string,body:unknown,projectId:string){let token:string;try{token=await this.secrets.get(this.tokenReference,projectId);}catch{throw new HumanActionRequired('Supabase Management API credential is not configured; use official OAuth/token issuance flow',{secretReference:this.tokenReference});}const response=await fetch(`${this.baseUrl}${path}`,{method,headers:{authorization:`Bearer ${token}`,'content-type':'application/json'},...(body===undefined?{}:{body:JSON.stringify(body)})});if(response.status===401||response.status===403)throw new HumanActionRequired('Supabase credential lacks the required scoped consent',{status:response.status});if(!response.ok)throw new ExecutionFailed('Supabase Management API operation failed',{status:response.status,body:(await response.text()).slice(0,500)});const text=await response.text();return text?JSON.parse(text):{};}
}
export class UnconfiguredSupabaseAdapter {readonly capability='NOT_CONFIGURED';async createSandboxProject():Promise<never>{throw new UnsupportedOperation('Supabase live adapter is not configured');}}
function assertOrganization(resource:Resource){if(resource.type!=='SUPABASE_ORGANIZATION'||resource.environment!=='SANDBOX'||resource.status!=='ACTIVE'||!resource.permissions.includes('ADMIN'))throw new PolicyViolation('Active SANDBOX SUPABASE_ORGANIZATION resource with ADMIN permission required');}
function assertProject(resource:Resource){if(resource.type!=='SUPABASE_PROJECT'||resource.environment!=='SANDBOX'||resource.status!=='ACTIVE')throw new PolicyViolation('Active SANDBOX SUPABASE_PROJECT resource required');}
function assertSandboxName(name:string){if(!/^(?:backend-autopilot|autopilot-sandbox)[a-z0-9-]*$/.test(name))throw new PolicyViolation('Sandbox project name must start with backend-autopilot or autopilot-sandbox');}
function supabaseEnvironment(){const configured=process.env['AUTOPILOT_SUPABASE_HOME']?.trim();if(!configured)throw new HumanActionRequired('An isolated Supabase credential home is required; default CLI credentials are never used',{environmentVariable:'AUTOPILOT_SUPABASE_HOME'});return {SUPABASE_HOME:resolve(process.cwd(),configured)};}
