import { spawn } from 'node:child_process';
import { Pool } from 'pg';
import type { Clock, StateStore } from '../../core/src/ports.js';
import type { SecretProvider } from '../../core/src/secrets.js';
import type { CapabilityStatus, RuntimeCapabilities } from '../../schemas/src/index.js';

type Probe={ok:boolean;stdout:string};
export class RuntimeCapabilityProbe {
  constructor(private store:StateStore,private secrets:SecretProvider,private clock:Clock){}
  async capture(projectId?:string):Promise<RuntimeCapabilities>{
    const capturedAt=this.clock.now();const git=await probe('git',['--version']);const gh=await probe('gh',['api','user','--jq','.login']);const supabase=await probe('supabase',['--version']);
    const evidence=projectId?await this.store.listAudit(projectId):[];const remote=evidence.find(e=>['bootstrap.github.repository_created','bootstrap.github.repository_initialized'].includes(e.action)&&resultSucceeded(e.result));const ci=evidence.find(e=>e.action==='bootstrap.github.ci_verified'&&resultSucceeded(e.result));const migration=evidence.find(e=>e.action==='bootstrap.database.migration_verified'&&resultSucceeded(e.result));
    let databaseStatus:CapabilityStatus='NOT_CONFIGURED',databaseDetail='No project-scoped DATABASE resource with a configured secret reference';let databaseTestedAt:string|undefined;
    if(projectId){const resource=(await this.store.listResources(projectId)).find(r=>r.type==='DATABASE'&&r.status==='ACTIVE');if(resource?.secretRefs[0]){databaseStatus='CONFIGURED';databaseDetail=`Registered ${resource.provider} database`;let pool:Pool|undefined;try{const url=await this.secrets.get(resource.secretRefs[0],projectId);pool=new Pool({connectionString:url,connectionTimeoutMillis:5_000});await pool.query('select 1 as ok');databaseStatus='LIVE_TESTED';databaseDetail=`Connected to registered ${resource.provider} database`;databaseTestedAt=capturedAt;}catch{databaseDetail='Database resource exists but live health check failed or its secret is unavailable';}finally{if(pool)await pool.end();}}}
    const item=(status:CapabilityStatus,detail:string,lastTestedAt?:string)=>({status,detail,...(lastTestedAt?{lastTestedAt}:{})});
    const supabaseAuthenticated=evidence.find(e=>['bootstrap.supabase.organization_registered','bootstrap.supabase.project_created','bootstrap.supabase.project_registered'].includes(e.action)&&resultSucceeded(e.result));const supabaseProject=evidence.find(e=>['bootstrap.supabase.project_created','bootstrap.supabase.project_registered'].includes(e.action)&&resultSucceeded(e.result));return {capturedAt,git:{local:item(git.ok?'LIVE_TESTED':'NOT_CONFIGURED',git.ok?git.stdout.trim():'Git CLI unavailable',git.ok?capturedAt:undefined),githubAuthentication:item(gh.ok?'CONFIGURED':'NOT_CONFIGURED',gh.ok?`Authenticated CLI account: ${gh.stdout.trim()}`:'GitHub CLI is not authenticated'),remoteWrite:item(remote?'LIVE_TESTED':'NOT_CONFIGURED',remote?'A sandbox repository creation/push is recorded':'No successful sandbox remote write is recorded',remote?.timestamp),ci:item(ci?'LIVE_TESTED':'NOT_CONFIGURED',ci?'A sandbox CI run is recorded':'No successful sandbox CI run is recorded',ci?.timestamp)},database:{externalPostgres:item(databaseStatus,databaseDetail,databaseTestedAt),migrations:item(migration?'LIVE_TESTED':databaseStatus==='LIVE_TESTED'?'SUPPORTED':'NOT_CONFIGURED',migration?'A live migration verification is recorded':'No live migration evidence is recorded',migration?.timestamp)},supabase:{adapter:item(supabase.ok?'SUPPORTED':'NOT_SUPPORTED',supabase.ok?`Supabase CLI ${supabase.stdout.trim()} and live adapter are installed`:'Supabase CLI unavailable'),authentication:item(supabaseAuthenticated?'LIVE_TESTED':process.env['AUTOPILOT_SUPABASE_ACCESS_TOKEN_REF']?'CONFIGURED':'NOT_CONFIGURED',supabaseAuthenticated?'Authenticated sandbox CLI session was used successfully':process.env['AUTOPILOT_SUPABASE_ACCESS_TOKEN_REF']?'Explicit runtime token reference is configured':'No explicit Supabase auth proof; existing projects were not enumerated',supabaseAuthenticated?.timestamp),projectCreation:item(supabaseProject?'LIVE_TESTED':'SUPPORTED',supabaseProject?'An explicitly allowlisted sandbox project was verified':'Live adapter implemented; evidence required',supabaseProject?.timestamp),rlsManagement:item(evidence.some(e=>e.action==='bootstrap.supabase.rls_verified')?'LIVE_TESTED':'SUPPORTED','Structured PostgreSQL RLS adapter implemented'),authManagement:item(evidence.some(e=>e.action==='bootstrap.supabase.auth_verified')?'LIVE_TESTED':'SUPPORTED','Management API adapter implemented'),storageManagement:item(evidence.some(e=>e.action==='bootstrap.supabase.storage_verified')?'LIVE_TESTED':'SUPPORTED','Management API adapter implemented')},providers:{neon:item('NOT_CONFIGURED','Provider-neutral PostgreSQL port exists; no Neon provisioning adapter or account is configured'),cloudflare:item('NOT_CONFIGURED','Provider-neutral infrastructure boundary exists; no Cloudflare live adapter or account is configured')}};
  }
}
function resultSucceeded(value:unknown){return !!value&&typeof value==='object'&&'success' in value&&(value as {success:unknown}).success===true;}
function probe(command:string,args:string[]):Promise<Probe>{return new Promise(resolve=>{const child=spawn(command,args,{shell:false,windowsHide:true,env:process.env});let stdout='';child.stdout.on('data',(v:Buffer)=>stdout+=v.toString());child.on('error',()=>resolve({ok:false,stdout:''}));child.on('close',code=>resolve({ok:code===0,stdout}));});}
