import type { Clock, CommandJournal, IdGenerator, StateStore } from '../../core/src/ports.js';
import { Conflict, HumanActionRequired, NotFound, PolicyViolation } from '../../core/src/errors.js';
import type { MutableSecretProvider } from '../../core/src/secrets.js';
import { PolicyEngine } from '../../policy-engine/src/index.js';
import { ArtifactStore } from '../../artifact-store/src/index.js';
import { AuditLog } from '../../audit/src/index.js';
import type { CredentialManifestEntry, InfrastructureManifestEntry, Resource } from '../../schemas/src/index.js';
import type { DestructiveAuthorization } from '../../schemas/src/index.js';
import type { LiveGitHubAdapter } from '../../adapters/github/src/index.js';
import type { ExternalPostgresAdapter, MigrationInput } from '../../adapters/database/src/index.js';
import type { LiveSupabaseCliAdapter, SupabaseManagementApiAdapter } from '../../adapters/supabase/src/index.js';
import type { RuntimeCapabilityProbe } from './capabilities.js';
import { renderInfrastructureManifest, renderSecretsManifest } from './manifests.js';

export interface SandboxBootstrapInput {projectId:string;operationId:string;githubAccountResourceId:string;githubRepositoryName:string;supabaseOrganizationResourceId:string;supabaseProjectName:string;region:string;migrations:MigrationInput[];rlsPolicies:{table:string;ownerColumn:string;policyName:string}[];authConfig?:{site_url?:string;disable_signup?:boolean;jwt_exp?:number;mailer_autoconfirm?:boolean};storageConfig?:{fileSizeLimit?:number;features?:Record<string,unknown>};waitForCi:boolean;}
export class SandboxBootstrapService {
  private policy:PolicyEngine;private artifacts:ArtifactStore;private audit:AuditLog;
  constructor(private deps:{store:StateStore;clock:Clock;ids:IdGenerator;commands:CommandJournal;secrets:MutableSecretProvider;github:LiveGitHubAdapter;supabase:LiveSupabaseCliAdapter;supabaseApi:SupabaseManagementApiAdapter;database:ExternalPostgresAdapter;capabilities:RuntimeCapabilityProbe}){this.policy=new PolicyEngine(deps.store);this.artifacts=new ArtifactStore(deps.store,deps.ids,deps.clock);this.audit=new AuditLog(deps.store,deps.ids,deps.clock);}
  runtimeCapabilities(projectId?:string){return this.deps.capabilities.capture(projectId);}
  async registerGithubIdentity(projectId:string,confirmedDedicatedSandbox:boolean){const project=await this.project(projectId);if(!confirmedDedicatedSandbox)throw new HumanActionRequired('Human confirmation is required that the active GitHub account is dedicated to Backend Autopilot sandbox use');if(project.autonomyMode!=='AUTONOMOUS_STAGING')throw new PolicyViolation('Identity bootstrap requires AUTONOMOUS_STAGING');const login=await this.deps.github.authenticatedIdentity(project.workspacePath,projectId);const existing=await this.deps.store.findResource(projectId,login);if(existing)return existing;return this.registerResource({type:'GITHUB_ACCOUNT',provider:'github',externalReference:login,projectId,environment:'SANDBOX',permissions:['READ','WRITE','ADMIN'],status:'ACTIVE',secretRefs:[]},'bootstrap.github.identity_registered');}
  async registerSupabaseOrganization(projectId:string,confirmedDedicatedSandbox:boolean){const project=await this.project(projectId);if(project.autonomyMode!=='AUTONOMOUS_STAGING')throw new PolicyViolation('Identity bootstrap requires AUTONOMOUS_STAGING');const organization=await this.deps.supabase.discoverOrganizations({cwd:project.workspacePath,projectId,confirmedDedicatedSandbox});const existing=await this.deps.store.findResource(projectId,organization.id);if(existing)return existing;return this.registerResource({type:'SUPABASE_ORGANIZATION',provider:'supabase',externalReference:organization.id,projectId,environment:'SANDBOX',permissions:['READ','WRITE','ADMIN'],status:'ACTIVE',secretRefs:[]},'bootstrap.supabase.organization_registered');}
  async bootstrap(input:SandboxBootstrapInput){
    const project=await this.project(input.projectId);if(project.autonomyMode!=='AUTONOMOUS_STAGING'||project.environment!=='STAGING')throw new PolicyViolation('Live sandbox bootstrap requires an AUTONOMOUS_STAGING project in STAGING environment');const prior=(await this.deps.store.listArtifacts(project.id)).find(a=>a.kind==='BOOTSTRAP_REPORT'&&(a.content as {operationId?:string}).operationId===input.operationId);if(prior)return {idempotentReplay:true,report:prior.content};const githubAccount=await this.resource(project.id,input.githubAccountResourceId);const supabaseOrganization=await this.resource(project.id,input.supabaseOrganizationResourceId);await this.policy.authorize({project,action:'PROVISION',resourceId:githubAccount.resourceId,requiredPermission:'ADMIN',actor:'bootstrap-agent'});await this.policy.authorize({project,action:'PROVISION',resourceId:supabaseOrganization.resourceId,requiredPermission:'ADMIN',actor:'bootstrap-agent'});
    const credentials:CredentialManifestEntry[]=[];const infrastructure:InfrastructureManifestEntry[]=[];const repositoryRef=`${githubAccount.externalReference}/${input.githubRepositoryName}`;let githubRepository=await this.deps.store.findResource(project.id,repositoryRef);let githubMetadata;
    if(!githubRepository){githubMetadata=await this.deps.github.createSandboxRepository(githubAccount,{workspace:project.workspacePath,name:input.githubRepositoryName,description:'Backend Autopilot live sandbox',correlationId:project.id});githubRepository=await this.registerResource({type:'GITHUB_REPOSITORY',provider:'github',externalReference:githubMetadata.nameWithOwner,projectId:project.id,environment:'SANDBOX',permissions:['READ','WRITE','ADMIN'],status:'ACTIVE',secretRefs:[]},'bootstrap.github.repository_created');await this.audit.record({actor:'bootstrap-agent',action:'bootstrap.github.repository_created',projectId:project.id,resourceId:githubRepository.resourceId,input:{operationId:input.operationId},result:{success:true,externalId:githubMetadata.nameWithOwner},reason:'Created explicitly named sandbox repository and pushed initialized workspace',correlationId:input.operationId});}else githubMetadata=await this.deps.github.metadata(githubAccount,project.workspacePath,repositoryRef,project.id);
    infrastructure.push({provider:'GitHub',account:githubAccount.externalReference,resourceType:'GITHUB_REPOSITORY',externalId:githubRepository.externalReference,projectId:project.id,environment:'SANDBOX',urls:[githubMetadata.url],createdAt:this.deps.clock.now(),purpose:'Backend Autopilot live sandbox repository',deletionProcedure:'Call sandbox_repository_delete with explicit DELETE_SANDBOX_REPOSITORY confirmation',status:'ACTIVE'});
    const existingSupabase=(await this.deps.store.listResources(project.id)).find(r=>r.type==='SUPABASE_PROJECT'&&r.provider==='supabase');let supabaseProject=existingSupabase;let databaseResource=(await this.deps.store.listResources(project.id)).find(r=>r.type==='DATABASE'&&r.provider==='supabase');
    if(!supabaseProject){const prefix=`AUTOPILOT_${project.slug.toUpperCase().replace(/[^A-Z0-9]+/g,'_')}`;const created=await this.deps.supabase.createSandboxProject(supabaseOrganization,{cwd:project.workspacePath,name:input.supabaseProjectName,region:input.region,secretPrefix:prefix,correlationId:project.id});supabaseProject=await this.registerResource({type:'SUPABASE_PROJECT',provider:'supabase',externalReference:created.ref,projectId:project.id,environment:'SANDBOX',permissions:['READ','WRITE','ADMIN','MIGRATE'],status:'ACTIVE',secretRefs:[created.passwordSecretRef]},'bootstrap.supabase.project_created');databaseResource=await this.registerResource({type:'DATABASE',provider:'supabase',externalReference:`supabase:${created.ref}:postgres`,projectId:project.id,environment:'SANDBOX',permissions:['READ','WRITE','MIGRATE'],status:'ACTIVE',secretRefs:[created.databaseSecretRef]},'bootstrap.database.resource_created');credentials.push({credentialName:created.passwordSecretRef,provider:'Supabase',purpose:'Sandbox project database credential',projectId:project.id,scope:`database project ${created.ref} only`,createdAt:this.deps.clock.now(),whereStored:'local .env (gitignored)',rotationMethod:'sandbox_credential_rotate semantic operation',revocationMethod:'delete sandbox project or revoke credential',status:'ACTIVE'},{credentialName:created.databaseSecretRef,provider:'Supabase/PostgreSQL',purpose:'Live sandbox database connection',projectId:project.id,scope:`database project ${created.ref} only`,createdAt:this.deps.clock.now(),whereStored:'local .env (gitignored)',rotationMethod:'sandbox_credential_rotate semantic operation',revocationMethod:'sandbox_credential_revoke or delete sandbox project',status:'ACTIVE'});await this.audit.record({actor:'bootstrap-agent',action:'bootstrap.supabase.project_created',projectId:project.id,resourceId:supabaseProject.resourceId,input:{operationId:input.operationId,region:input.region},result:{success:true,externalId:created.ref},reason:'Created explicitly authorized Supabase sandbox project',correlationId:input.operationId});}
    if(!databaseResource||!supabaseProject)throw new Conflict('Bootstrap could not establish database resources');await this.policy.authorize({project,action:'MIGRATE',resourceId:databaseResource.resourceId,requiredPermission:'MIGRATE',actor:'bootstrap-agent'});await this.waitForDatabase(databaseResource);const migrationResults=await this.deps.database.applyMigrations(databaseResource,input.migrations);for(const policy of input.rlsPolicies){await this.deps.database.enableRls(databaseResource,policy.table);await this.deps.database.createOwnershipPolicy(databaseResource,{...policy,dialect:'SUPABASE'});}const schema=await this.deps.database.inspectSchema(databaseResource);await this.audit.record({actor:'bootstrap-agent',action:'bootstrap.database.migration_verified',projectId:project.id,resourceId:databaseResource.resourceId,input:{migrations:input.migrations.map(m=>m.name)},result:{success:true,migrationResults},reason:'Live migration and schema inspection completed',correlationId:input.operationId});if(input.rlsPolicies.length)await this.audit.record({actor:'bootstrap-agent',action:'bootstrap.supabase.rls_verified',projectId:project.id,resourceId:supabaseProject.resourceId,input:{tables:input.rlsPolicies.map(p=>p.table)},result:{success:true},reason:'RLS policies applied through structured adapter',correlationId:input.operationId});
    if(input.authConfig){await this.deps.supabaseApi.updateAuth(supabaseProject,input.authConfig);await this.audit.record({actor:'bootstrap-agent',action:'bootstrap.supabase.auth_verified',projectId:project.id,resourceId:supabaseProject.resourceId,input:{fields:Object.keys(input.authConfig)},result:{success:true},reason:'Auth configuration updated through Management API',correlationId:input.operationId});}if(input.storageConfig){await this.deps.supabaseApi.updateStorage(supabaseProject,input.storageConfig);await this.audit.record({actor:'bootstrap-agent',action:'bootstrap.supabase.storage_verified',projectId:project.id,resourceId:supabaseProject.resourceId,input:{fields:Object.keys(input.storageConfig)},result:{success:true},reason:'Storage configuration updated through Management API',correlationId:input.operationId});}
    infrastructure.push({provider:'Supabase',account:'dedicated sandbox account',organization:supabaseOrganization.externalReference,resourceType:'SUPABASE_PROJECT',externalId:supabaseProject.externalReference,projectId:project.id,environment:'SANDBOX',urls:[`https://supabase.com/dashboard/project/${supabaseProject.externalReference}`],createdAt:this.deps.clock.now(),purpose:'Backend Autopilot live sandbox database',deletionProcedure:'Call sandbox_database_delete with explicit DELETE_SANDBOX_DATABASE confirmation',status:'ACTIVE'});const ci=await this.deps.github.ciStatus(githubRepository,{workspace:project.workspacePath,branch:githubMetadata.defaultBranch,correlationId:project.id,wait:input.waitForCi});if(ci.success)await this.audit.record({actor:'bootstrap-agent',action:'bootstrap.github.ci_verified',projectId:project.id,resourceId:githubRepository.resourceId,input:{branch:githubMetadata.defaultBranch},result:{success:true,ci},reason:'GitHub Actions completed successfully',correlationId:input.operationId});await this.persistCommands(project.id);const secretsArtifact=await this.artifacts.write(project.id,'SECRETS_MANIFEST',{entries:credentials,markdown:renderSecretsManifest(credentials)});const infrastructureArtifact=await this.artifacts.write(project.id,'INFRASTRUCTURE_MANIFEST',{entries:infrastructure,markdown:renderInfrastructureManifest(infrastructure)});const capabilities=await this.runtimeCapabilities(project.id);await this.artifacts.write(project.id,'CAPABILITY_SNAPSHOT',capabilities);const report={operationId:input.operationId,success:ci.success,repository:githubMetadata,database:{provider:'supabase',projectRef:supabaseProject.externalReference,migrations:migrationResults,schema},ci,secretManifestArtifactId:secretsArtifact.id,infrastructureManifestArtifactId:infrastructureArtifact.id,completedAt:this.deps.clock.now()};await this.artifacts.write(project.id,'BOOTSTRAP_REPORT',report);await this.audit.record({actor:'bootstrap-agent',action:'bootstrap.complete',projectId:project.id,input:{operationId:input.operationId},result:{success:ci.success},reason:'Sandbox infrastructure bootstrap completed',correlationId:input.operationId});return {idempotentReplay:false,report};
  }
  async deleteRepository(projectId:string,authorization:DestructiveAuthorization){const project=await this.project(projectId);const resource=await this.resource(projectId,authorization.resourceId);await this.policy.authorize({project,action:'DESTRUCTIVE',resourceId:resource.resourceId,requiredPermission:'ADMIN',actor:'bootstrap-agent'});const result=await this.deps.github.deleteSandboxRepository(resource,authorization,{cwd:project.workspacePath,correlationId:project.id});await this.deps.store.updateResource({...resource,status:'DISABLED'});await this.audit.record({actor:'bootstrap-agent',action:'sandbox.repository_deleted',projectId,resourceId:resource.resourceId,input:{operationId:authorization.operationId},result,reason:'Explicit semantic destructive operation',correlationId:authorization.operationId});return result;}
  async deleteDatabase(projectId:string,authorization:DestructiveAuthorization){const project=await this.project(projectId);const resource=await this.resource(projectId,authorization.resourceId);await this.policy.authorize({project,action:'DESTRUCTIVE',resourceId:resource.resourceId,requiredPermission:'ADMIN',actor:'bootstrap-agent'});const result=await this.deps.supabase.deleteSandboxProject(resource,authorization,{cwd:project.workspacePath,correlationId:project.id});await this.deps.store.updateResource({...resource,status:'DISABLED'});await this.audit.record({actor:'bootstrap-agent',action:'sandbox.database_deleted',projectId,resourceId:resource.resourceId,input:{operationId:authorization.operationId},result,reason:'Explicit semantic destructive operation',correlationId:authorization.operationId});return result;}
  private async registerResource(input:Omit<Resource,'resourceId'|'createdAt'>,action:string){const resource:Resource={...input,resourceId:this.deps.ids.next(),createdAt:this.deps.clock.now()};await this.deps.store.createResource(resource);await this.audit.record({actor:'bootstrap-agent',action:'resource_created',projectId:resource.projectId,resourceId:resource.resourceId,input:{provider:resource.provider,externalId:resource.externalReference,permissions:resource.permissions},result:{success:true,type:resource.type,bootstrapAction:action},reason:'Automatically created and allowlisted sandbox resource',correlationId:this.deps.ids.next()});return resource;}
  private async project(id:string){const project=await this.deps.store.getProject(id);if(!project)throw new NotFound('Project not found');return project;}
  private async resource(projectId:string,id:string){const resource=await this.deps.store.getResource(id);if(!resource)throw new NotFound('Resource not found');if(resource.projectId!==projectId)throw new PolicyViolation('Cross-project bootstrap resource denied');return resource;}
  private async persistCommands(projectId:string){const entries=this.deps.commands.drain(projectId);if(!entries.length)return;await this.artifacts.write(projectId,'COMMAND_LOG',{commands:entries.map(e=>({...e.record,stdout:e.stdout,stderr:e.stderr}))});}
  private async waitForDatabase(resource:Resource){for(let attempt=0;attempt<30;attempt++){try{return await this.deps.database.health(resource);}catch{if(attempt===29)throw new Conflict('Sandbox database did not become reachable within bootstrap timeout');await new Promise(resolve=>setTimeout(resolve,5_000));}}throw new Conflict('Sandbox database unavailable');}
}
