import 'dotenv/config';
import { createHash } from 'node:crypto';
import { readFile } from 'node:fs/promises';
import { resolve } from 'node:path';
import { Pool, type PoolClient } from 'pg';
import type { Artifact, AuditEvent, Project, ProjectContext, Resource, Run, Task, Transition } from '../packages/schemas/src/index.js';

interface Snapshot {projects:Project[];resources:Resource[];contexts:ProjectContext[];tasks:Task[];artifacts:Artifact[];runs:Run[];transitions:Transition[];audit:AuditEvent[];}
const source=resolve(argument('--source')??'.autopilot/state.json'),databaseUrl=process.env['DATABASE_URL'];if(!databaseUrl)throw new Error('DATABASE_URL is required');const raw=await readFile(source,'utf8'),checksum=createHash('sha256').update(raw).digest('hex'),marker=`file-state:${checksum}`;const snapshot=JSON.parse(raw) as Snapshot;const pool=new Pool({connectionString:databaseUrl});const client=await pool.connect();
try{await client.query('begin');const existing=await client.query('select data from migration_markers where key=$1',[marker]);if(existing.rowCount){await verify(client,snapshot);await client.query('rollback');console.log(JSON.stringify({event:'state.migration.replay',marker,source}));process.exitCode=0;}else{for(const project of snapshot.projects){const repository=snapshot.resources.find(value=>value.projectId===project.id&&value.type==='GITHUB_REPOSITORY'&&value.status==='ACTIVE');const [owner,name]=repository?.externalReference.split('/')??[];const migrated:Project={...project,workspacePath:'',...(owner&&name&&repository?{repository:{owner,name,defaultBranch:'main',resourceId:repository.resourceId}}:{})};await client.query('insert into projects(id,slug,data,created_at) values($1,$2,$3,$4) on conflict(id) do nothing',[migrated.id,migrated.slug,migrated,migrated.createdAt]);}for(const value of snapshot.resources)await insert(client,'resources',['id','project_id','provider','external_reference','data','created_at'],[value.resourceId,value.projectId,value.provider,value.externalReference,value,value.createdAt]);for(const value of snapshot.contexts)await insert(client,'project_contexts',['id','project_id','data','created_at'],[value.id,value.projectId,value,value.createdAt]);for(const value of snapshot.tasks)await insert(client,'tasks',['id','project_id','external_key','data','created_at'],[value.id,value.projectId,value.externalKey,value,value.createdAt]);for(const value of snapshot.runs)await insert(client,'runs',['id','project_id','task_id','operation_id','data','created_at'],[value.id,value.projectId,value.taskId,value.operationId,value,value.startedAt]);for(const artifact of snapshot.artifacts){const value:Artifact={...artifact,status:artifact.status??'AVAILABLE'};await insert(client,'artifacts',['id','project_id','task_id','run_id','kind','status','content_hash','data','created_at'],[value.id,value.projectId,value.taskId??null,value.runId??null,value.kind,value.status,value.contentHash,value,value.createdAt]);}for(const value of snapshot.transitions)await insert(client,'task_transitions',['id','task_id','data','created_at'],[value.id,value.taskId,value,value.timestamp]);for(const value of snapshot.audit)await insert(client,'audit_events',['id','project_id','data','created_at'],[value.id,value.projectId,value,value.timestamp]);await verify(client,snapshot);await client.query('insert into migration_markers(key,checksum,data,created_at) values($1,$2,$3,now())',[marker,checksum,{source,counts:counts(snapshot)}]);await client.query('commit');console.log(JSON.stringify({event:'state.migration.complete',marker,source,counts:counts(snapshot)}));}}catch(error){await client.query('rollback');throw error;}finally{client.release();await pool.end();}
async function insert(client:PoolClient,table:string,columns:string[],values:unknown[]){const params=values.map((_,index)=>`$${index+1}`).join(',');await client.query(`insert into ${table}(${columns.join(',')}) values(${params}) on conflict do nothing`,values);}
async function verify(client:PoolClient,snapshot:Snapshot){for(const [table,minimum] of Object.entries({projects:snapshot.projects.length,resources:snapshot.resources.length,project_contexts:snapshot.contexts.length,tasks:snapshot.tasks.length,artifacts:snapshot.artifacts.length,runs:snapshot.runs.length,task_transitions:snapshot.transitions.length,audit_events:snapshot.audit.length})){const result=await client.query<{count:string}>(`select count(*)::text as count from ${table}`);if(Number(result.rows[0]?.count??0)<minimum)throw new Error(`State migration verification failed for ${table}`);}}
function counts(value:Snapshot){return {projects:value.projects.length,resources:value.resources.length,contexts:value.contexts.length,tasks:value.tasks.length,artifacts:value.artifacts.length,runs:value.runs.length,transitions:value.transitions.length,audit:value.audit.length};}
function argument(name:string){const index=process.argv.indexOf(name);return index>=0?process.argv[index+1]:undefined;}
