import 'jsr:@supabase/functions-js/edge-runtime.d.ts';
import { McpServer } from 'npm:@modelcontextprotocol/sdk@1.25.3/server/mcp.js';
import { WebStandardStreamableHTTPServerTransport } from 'npm:@modelcontextprotocol/sdk@1.25.3/server/webStandardStreamableHttp.js';
import { z } from 'npm:zod@3.25.76';
import { autonomyModeSchema, contextSectionTypeSchema, environmentSchema, fileChangeSchema, relationshipTypeSchema, resourcePermissionSchema, resourceTypeSchema } from '../../../packages/schemas/src/index.ts';
import { createEdgeRuntime, mcpProjectAllowed, required } from '../_shared/edge-runtime.ts';

Deno.serve(async request=>{if(!(await authorized(request)))return new Response(JSON.stringify({error:'unauthorized'}),{status:401,headers:{'content-type':'application/json','www-authenticate':'Bearer'}});const runtime=createEdgeRuntime();const server=new McpServer({name:'backend-autopilot',version:'0.4.0'});const ro={readOnlyHint:true,destructiveHint:false,openWorldHint:false},mut={readOnlyHint:false,destructiveHint:false,openWorldHint:false};const result=(value:unknown)=>({content:[{type:'text' as const,text:JSON.stringify(value)}],structuredContent:{result:value}});const scoped=(projectId:string)=>{if(!mcpProjectAllowed(projectId))throw new Error('MCP token is not authorized for this project');};
  server.registerTool('system_health',{description:'Return remote control-plane health',inputSchema:{},annotations:ro},async()=>result(await runtime.service.systemHealth()));
  server.registerTool('project_list',{description:'List MCP-allowlisted projects',inputSchema:{},annotations:ro},async()=>result((await runtime.service.projectList()).filter(value=>mcpProjectAllowed(value.id))));
  server.registerTool('project_get',{description:'Get an allowlisted project',inputSchema:{projectId:z.string().uuid()},annotations:ro},async({projectId})=>{scoped(projectId);return result(await runtime.service.projectGet(projectId));});
  server.registerTool('resource_list',{description:'List registered resources',inputSchema:{projectId:z.string().uuid()},annotations:ro},async({projectId})=>{scoped(projectId);return result(await runtime.service.resourceList(projectId));});
  server.registerTool('resource_register',{description:'Register one explicit non-production resource',inputSchema:{projectId:z.string().uuid(),type:resourceTypeSchema,provider:z.string(),externalReference:z.string(),environment:environmentSchema,permissions:z.array(resourcePermissionSchema),secretRefs:z.array(z.string()).default([]),status:z.enum(['ACTIVE','DISABLED']).default('ACTIVE')},annotations:mut},async value=>{scoped(value.projectId);return result(await runtime.service.resourceRegister(value,'remote-mcp'));});
  server.registerTool('context_get',{description:'Read structured project context',inputSchema:{projectId:z.string().uuid()},annotations:ro},async({projectId})=>{scoped(projectId);return result(await runtime.service.contextGet(projectId));});
  server.registerTool('context_import',{description:'Import structured untrusted context',inputSchema:{projectId:z.string().uuid(),items:z.array(z.object({type:contextSectionTypeSchema,content:z.unknown(),sourceType:z.enum(['TASK_SOURCE','FILE','MCP','USER','REPOSITORY','DECISION']),sourceRef:z.string()}))},annotations:mut},async value=>{scoped(value.projectId);return result(await runtime.service.contextImport(value.projectId,value.items,'remote-mcp'));});
  server.registerTool('task_create',{description:'Create task',inputSchema:{projectId:z.string().uuid(),externalKey:z.string(),title:z.string(),description:z.string(),requirements:z.array(z.string()),relationships:z.array(z.object({type:relationshipTypeSchema,targetTaskId:z.string().uuid()})).default([])},annotations:mut},async value=>{scoped(value.projectId);return result(await runtime.service.taskCreate(value,'remote-mcp'));});
  server.registerTool('task_get',{description:'Get task',inputSchema:{projectId:z.string().uuid(),taskId:z.string().uuid()},annotations:ro},async({projectId,taskId})=>{scoped(projectId);return result(await runtime.service.taskGet(projectId,taskId));});
  server.registerTool('task_list',{description:'List project tasks',inputSchema:{projectId:z.string().uuid()},annotations:ro},async({projectId})=>{scoped(projectId);return result(await runtime.service.taskList(projectId));});
  server.registerTool('task_analyze',{description:'Analyze dependencies',inputSchema:{projectId:z.string().uuid(),taskId:z.string().uuid()},annotations:mut},async({projectId,taskId})=>{scoped(projectId);return result(await runtime.service.taskAnalyze(projectId,taskId,'remote-mcp'));});
  server.registerTool('task_plan',{description:'Create and guard implementation plan',inputSchema:{projectId:z.string().uuid(),taskId:z.string().uuid()},annotations:mut},async({projectId,taskId})=>{scoped(projectId);return result(await runtime.service.taskPlan(projectId,taskId,'remote-mcp'));});
  server.registerTool('task_execute',{description:'Queue asynchronous GitHub Actions implementation job',inputSchema:{projectId:z.string().uuid(),taskId:z.string().uuid(),resourceId:z.string().uuid(),operationId:z.string().min(8),changes:z.array(fileChangeSchema)},annotations:{...mut,idempotentHint:true,openWorldHint:true}},async value=>{scoped(value.projectId);return result(await runtime.asyncExecution.enqueueImplementation(value,value.resourceId,'remote-mcp'));});
  server.registerTool('task_review',{description:'Run independent READY gates after remote tests',inputSchema:{projectId:z.string().uuid(),taskId:z.string().uuid()},annotations:mut},async({projectId,taskId})=>{scoped(projectId);return result(await runtime.service.taskReview(projectId,taskId,'remote-mcp'));});
  server.registerTool('task_retry',{description:'Retry blocked or failed task',inputSchema:{projectId:z.string().uuid(),taskId:z.string().uuid()},annotations:mut},async({projectId,taskId})=>{scoped(projectId);return result(await runtime.service.taskRetry(projectId,taskId,'remote-mcp'));});
  server.registerTool('task_status',{description:'Read task lifecycle and durable jobs',inputSchema:{projectId:z.string().uuid(),taskId:z.string().uuid()},annotations:ro},async({projectId,taskId})=>{scoped(projectId);return result({...await runtime.service.taskStatus(projectId,taskId),jobs:await runtime.asyncExecution.list(projectId,taskId)});});
  server.registerTool('artifact_list',{description:'List artifact metadata',inputSchema:{projectId:z.string().uuid(),taskId:z.string().uuid().optional()},annotations:ro},async({projectId,taskId})=>{scoped(projectId);return result(await runtime.service.artifactList(projectId,taskId));});
  server.registerTool('artifact_read',{description:'Read durable artifact, hydrating Storage blobs',inputSchema:{projectId:z.string().uuid(),artifactId:z.string().uuid()},annotations:ro},async({projectId,artifactId})=>{scoped(projectId);return result(await runtime.service.artifactRead(projectId,artifactId));});
  server.registerTool('run_list',{description:'List task runs',inputSchema:{projectId:z.string().uuid(),taskId:z.string().uuid().optional()},annotations:ro},async({projectId,taskId})=>{scoped(projectId);return result(await runtime.service.runList(projectId,taskId));});
  server.registerTool('run_get',{description:'Read one run',inputSchema:{projectId:z.string().uuid(),runId:z.string().uuid()},annotations:ro},async({projectId,runId})=>{scoped(projectId);return result(await runtime.service.runGet(projectId,runId));});
  server.registerTool('job_list',{description:'List asynchronous execution jobs',inputSchema:{projectId:z.string().uuid(),taskId:z.string().uuid().optional()},annotations:ro},async({projectId,taskId})=>{scoped(projectId);return result(await runtime.asyncExecution.list(projectId,taskId));});
  server.registerTool('job_get',{description:'Read asynchronous execution job',inputSchema:{projectId:z.string().uuid(),jobId:z.string().uuid()},annotations:ro},async({projectId,jobId})=>{scoped(projectId);return result(await runtime.asyncExecution.get(projectId,jobId));});
  server.registerTool('project_snapshot',{description:'Read reproducible project snapshot',inputSchema:{projectId:z.string().uuid()},annotations:ro},async({projectId})=>{scoped(projectId);return result(await runtime.service.projectSnapshot(projectId));});
  server.registerTool('runtime_status',{description:'Return production runtime composition',inputSchema:{},annotations:ro},async()=>result({controlPlane:'SUPABASE',execution:'GITHUB_ACTIONS',console:'GITHUB_PAGES',alwaysOnServer:false,productionWrites:'NOT_SUPPORTED'}));
  const transport=new WebStandardStreamableHTTPServerTransport({sessionIdGenerator:undefined});await server.connect(transport);return transport.handleRequest(request);});

async function authorized(request:Request){const supplied=request.headers.get('authorization')?.replace(/^Bearer\s+/i,'')??'',expected=required('AUTOPILOT_MCP_TOKEN');const [left,right]=await Promise.all([digest(supplied),digest(expected)]);if(left.length!==right.length)return false;let difference=0;for(let index=0;index<left.length;index++)difference|=left[index]!^right[index]!;return difference===0;}
async function digest(value:string){return new Uint8Array(await crypto.subtle.digest('SHA-256',new TextEncoder().encode(value)));}
