import { Command } from 'commander';
import { readFile } from 'node:fs/promises';
import { createRuntime, DomainError } from '../../../packages/core/src/index.js';
import type { SandboxBootstrapInput } from '../../../packages/bootstrap/src/index.js';
import { redact } from '../../../packages/audit/src/index.js';
const {service,bootstrap}=createRuntime();const cli=new Command().name('autopilot').description('Backend Autopilot v0.4 diagnostic and sandbox bootstrap CLI').version('0.4.0');
const print=(v:unknown)=>console.log(JSON.stringify(v,null,2));const run=(fn:()=>Promise<unknown>)=>async()=>print(await fn());
cli.command('health').action(run(()=>service.systemHealth()));
cli.command('projects').action(run(()=>service.projectList()));
cli.command('project-create').requiredOption('--name <name>').requiredOption('--slug <slug>').requiredOption('--workspace <path>').option('--mode <mode>','autonomy mode','GUARDED').action(async o=>print(await service.projectCreate({name:o.name,slug:o.slug,sourceType:'LOCAL',environment:'SANDBOX',autonomyMode:o.mode,workspacePath:o.workspace})));
cli.command('resources').requiredOption('--project <id>').action(async o=>print(await service.resourceList(o.project)));
cli.command('tasks').requiredOption('--project <id>').action(async o=>print(await service.taskList(o.project)));
cli.command('task-create').requiredOption('--project <id>').requiredOption('--key <key>').requiredOption('--title <title>').requiredOption('--requirement <text>').action(async o=>print(await service.taskCreate({projectId:o.project,externalKey:o.key,title:o.title,description:o.title,requirements:[o.requirement],relationships:[]})));
cli.command('task-analyze').requiredOption('--project <id>').requiredOption('--task <id>').action(async o=>print(await service.taskAnalyze(o.project,o.task)));
cli.command('task-plan').requiredOption('--project <id>').requiredOption('--task <id>').action(async o=>print(await service.taskPlan(o.project,o.task)));
cli.command('task-execute').requiredOption('--project <id>').requiredOption('--task <id>').requiredOption('--resource <id>').requiredOption('--operation <id>').requiredOption('--changes <json-file>').action(async o=>print(await service.taskExecute({projectId:o.project,taskId:o.task,operationId:o.operation,changes:JSON.parse(await readFile(o.changes,'utf8'))},o.resource)));
cli.command('task-test').requiredOption('--project <id>').requiredOption('--task <id>').action(async o=>print(await service.taskTest(o.project,o.task)));
cli.command('task-review').requiredOption('--project <id>').requiredOption('--task <id>').action(async o=>print(await service.taskReview(o.project,o.task)));
cli.command('task-status').requiredOption('--project <id>').requiredOption('--task <id>').action(async o=>print(await service.taskStatus(o.project,o.task)));
cli.command('task-retry').requiredOption('--project <id>').requiredOption('--task <id>').action(async o=>print(await service.taskRetry(o.project,o.task)));
cli.command('artifacts').requiredOption('--project <id>').option('--task <id>').action(async o=>print(await service.artifactList(o.project,o.task)));
cli.command('capabilities').option('--project <id>').action(async o=>print(await bootstrap.runtimeCapabilities(o.project)));
cli.command('sandbox-github-register').requiredOption('--project <id>').requiredOption('--expected-login <login>').requiredOption('--confirm-dedicated-sandbox').action(async o=>print(await bootstrap.registerGithubIdentity(o.project,o.confirmDedicatedSandbox===true,o.expectedLogin)));
cli.command('sandbox-github-repository-register').requiredOption('--project <id>').requiredOption('--account-resource <id>').requiredOption('--repository <owner/name>').requiredOption('--confirm-explicit-sandbox-target').action(async o=>print(await bootstrap.registerGithubRepository(o.project,o.accountResource,o.repository,o.confirmExplicitSandboxTarget===true)));
cli.command('sandbox-supabase-register').requiredOption('--project <id>').requiredOption('--confirm-dedicated-sandbox').action(async o=>print(await bootstrap.registerSupabaseOrganization(o.project,o.confirmDedicatedSandbox===true)));
cli.command('sandbox-supabase-project-register').requiredOption('--project <id>').requiredOption('--organization-resource <id>').requiredOption('--expected-project-ref <ref>').requiredOption('--confirm-explicit-sandbox-target').action(async o=>print(await bootstrap.registerSupabaseProject(o.project,o.organizationResource,o.expectedProjectRef,o.confirmExplicitSandboxTarget===true)));
cli.command('sandbox-supabase-database-configure').requiredOption('--project <id>').requiredOption('--supabase-project-resource <id>').requiredOption('--confirm-credential-rotation').action(async o=>print(await bootstrap.configureExistingSupabaseDatabase(o.project,o.supabaseProjectResource,o.confirmCredentialRotation===true)));
cli.command('sandbox-github-ci-verify').requiredOption('--project <id>').requiredOption('--task <id>').requiredOption('--repository-resource <id>').requiredOption('--branch <name>').requiredOption('--expected-sha <sha>').action(async o=>print(await bootstrap.verifyGithubCi(o.project,o.task,o.repositoryResource,o.branch,o.expectedSha)));
cli.command('sandbox-github-pull-request-open').requiredOption('--project <id>').requiredOption('--task <id>').requiredOption('--repository-resource <id>').requiredOption('--base <branch>').requiredOption('--head <branch>').requiredOption('--title <text>').requiredOption('--body <text>').action(async o=>print(await bootstrap.openGithubPullRequest(o.project,o.task,o.repositoryResource,o.base,o.head,o.title,o.body)));
cli.command('sandbox-bootstrap').requiredOption('--file <json>').action(async o=>print(await bootstrap.bootstrap(JSON.parse(await readFile(o.file,'utf8')) as SandboxBootstrapInput)));
try{await cli.parseAsync();}catch(error){if(error instanceof DomainError){console.error(JSON.stringify({error:{code:error.code,message:error.message,details:redact(error.details)}},null,2));process.exitCode=1;}else throw error;}
